<?php
namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeds the blogs table with sample solar power and green energy blog posts
 */
class BlogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $now = Carbon::now();

        // Get user IDs (authors) - use first user (admin)
        $adminUserId = 1;

        // Get category IDs
        $solarPanelsCatId = DB::table('categories')->where('slug', 'solar-panels')->value('id');
        $invertersCatId   = DB::table('categories')->where('slug', 'inverters')->value('id');
        $batteriesCatId   = DB::table('categories')->where('slug', 'batteries')->value('id');
        $kitsCatId        = DB::table('categories')->where('slug', 'complete-kits')->value('id');

        $blogs = [
            [
                'title'            => 'The Ultimate Guide to Choosing Solar Panels for Your Home',
                'slug'             => 'ultimate-guide-choosing-solar-panels-home',
                'excerpt'          => 'Discover everything you need to know about selecting the perfect solar panels for your residential installation, from efficiency ratings to warranty considerations.',
                'content'          => '<p>Choosing the right solar panels for your home is one of the most important decisions in your renewable energy journey. With so many options available, it can be overwhelming. This comprehensive guide will help you make an informed decision.</p>

<h2>Understanding Solar Panel Types</h2>
<p>There are three main types of solar panels available today:</p>
<ul>
<li><strong>Monocrystalline</strong> - High efficiency (18-22%), sleek black appearance, best space efficiency</li>
<li><strong>Polycrystalline</strong> - Good efficiency (15-18%), blue color, more affordable</li>
<li><strong>Thin-Film</strong> - Lower efficiency (10-12%), flexible, lightweight</li>
</ul>

<h2>Key Factors to Consider</h2>
<h3>1. Efficiency Rating</h3>
<p>Higher efficiency means more power in less space. For limited roof space, opt for monocrystalline panels with 20%+ efficiency.</p>

<h3>2. Warranty Coverage</h3>
<p>Look for panels with at least a 25-year performance warranty and 10-12 year product warranty. This ensures long-term reliability.</p>

<h3>3. Temperature Coefficient</h3>
<p>Solar panels lose efficiency in high heat. A lower temperature coefficient (around -0.3%/°C) means better performance in hot climates.</p>

<h3>4. Budget Considerations</h3>
<p>While monocrystalline panels cost more upfront, their higher efficiency often results in better long-term value.</p>

<h2>Installation Considerations</h2>
<p>Proper installation is crucial for optimal performance. Ensure your installer is certified and experienced. Consider factors like:</p>
<ul>
<li>Roof orientation and tilt angle</li>
<li>Shading from trees or buildings</li>
<li>Local weather patterns</li>
<li>Available roof space</li>
</ul>

<h2>Conclusion</h2>
<p>Investing in quality solar panels is an investment in your future. Take time to research, compare options, and consult with professionals to make the best choice for your home.</p>',
                'category_id'      => $solarPanelsCatId,
                'author_id'        => $adminUserId,
                'featured_image'   => null,
                'meta_title'       => 'Complete Guide to Choosing Solar Panels for Your Home 2025',
                'meta_description' => 'Learn how to choose the best solar panels for your home. Compare types, efficiency, warranties, and make an informed decision.',
                'meta_keywords'    => 'solar panels, home solar, monocrystalline, polycrystalline, solar panel guide',
                'views'            => 1247,
                'is_published'     => true,
                'published_at'     => $now->copy()->subDays(30),
                'created_at'       => $now->copy()->subDays(30),
                'updated_at'       => $now->copy()->subDays(30),
            ],
            [
                'title'            => 'Solar Battery Storage: Is It Worth the Investment?',
                'slug'             => 'solar-battery-storage-worth-investment',
                'excerpt'          => 'Explore the benefits, costs, and considerations of adding battery storage to your solar power system. Learn if it\'s the right choice for your home.',
                'content'          => '<p>Battery storage has become increasingly popular with solar installations, but is it worth the investment? Let\'s break down the facts.</p>

<h2>What is Solar Battery Storage?</h2>
<p>Solar batteries store excess energy generated by your solar panels during the day for use at night or during power outages. They provide energy independence and security.</p>

<h2>Benefits of Battery Storage</h2>
<ul>
<li><strong>Energy Independence</strong> - Reduce reliance on the grid and protect against outages</li>
<li><strong>Maximize Solar Usage</strong> - Use your own solar power 24/7 instead of feeding excess to the grid</li>
<li><strong>Cost Savings</strong> - Avoid peak electricity rates by using stored power</li>
<li><strong>Environmental Impact</strong> - Increase your renewable energy usage to 90%+</li>
</ul>

<h2>Cost Considerations</h2>
<p>A typical 10kWh battery system costs between KSH 600,000 - 900,000 including installation. While this seems expensive, consider:</p>
<ul>
<li>Average payback period of 8-12 years</li>
<li>Increasing electricity rates improve ROI</li>
<li>Battery costs are decreasing year over year</li>
</ul>

<h2>Who Should Get Battery Storage?</h2>
<p>Battery storage makes most sense if you:</p>
<ul>
<li>Experience frequent power outages</li>
<li>Have high evening electricity usage</li>
<li>Want energy independence</li>
<li>Live in areas with time-of-use rates</li>
</ul>

<h2>Technology Comparison</h2>
<h3>Lithium-Ion Batteries</h3>
<p>Most popular choice. High efficiency (90-95%), 10+ year lifespan, 5000+ cycles.</p>

<h3>Lead-Acid Batteries</h3>
<p>Traditional option. Lower cost but shorter lifespan (3-5 years) and lower efficiency (80-85%).</p>

<h2>Final Verdict</h2>
<p>While battery storage requires significant upfront investment, it offers valuable benefits including energy security, independence, and long-term savings. For homes with high electricity usage or frequent outages, it\'s definitely worth considering.</p>',
                'category_id'      => $batteriesCatId,
                'author_id'        => $adminUserId,
                'featured_image'   => null,
                'meta_title'       => 'Solar Battery Storage Guide 2025 - Is It Worth It?',
                'meta_description' => 'Comprehensive guide to solar battery storage. Learn about costs, benefits, and whether battery storage is worth the investment.',
                'meta_keywords'    => 'solar battery, battery storage, lithium battery, energy storage, solar investment',
                'views'            => 892,
                'is_published'     => true,
                'published_at'     => $now->copy()->subDays(25),
                'created_at'       => $now->copy()->subDays(25),
                'updated_at'       => $now->copy()->subDays(25),
            ],
            [
                'title'            => 'Top 5 Benefits of Going Solar in 2025',
                'slug'             => 'top-5-benefits-going-solar-2025',
                'excerpt'          => 'Discover the compelling reasons why 2025 is the perfect time to switch to solar power. From financial savings to environmental impact, explore all the benefits.',
                'content'          => '<p>Solar energy has never been more accessible or affordable. Here are the top 5 reasons why you should consider going solar in 2025.</p>

<h2>1. Significant Cost Savings</h2>
<p>Solar panels can reduce your electricity bills by 50-90%. With a typical residential system:</p>
<ul>
<li>Average savings: KSH 3,000-7,000 per month</li>
<li>ROI period: 5-7 years</li>
<li>25+ year lifespan means 15+ years of free electricity</li>
</ul>

<h2>2. Increased Property Value</h2>
<p>Homes with solar installations sell for 4-5% more than comparable homes without solar. That\'s an average increase of KSH 500,000-1,000,000 in property value.</p>

<h2>3. Energy Independence</h2>
<p>Generate your own clean power and reduce dependence on utility companies. With battery storage, you can achieve near-complete energy independence.</p>

<h2>4. Environmental Impact</h2>
<p>A typical 5kW solar system offsets:</p>
<ul>
<li>6-8 tons of CO2 annually</li>
<li>Equivalent to planting 150-200 trees per year</li>
<li>Reduces your carbon footprint by 40-60%</li>
</ul>

<h2>5. Low Maintenance & Long Lifespan</h2>
<p>Solar panels require minimal maintenance:</p>
<ul>
<li>Occasional cleaning (rain usually sufficient)</li>
<li>Annual inspection recommended</li>
<li>25-30 year performance warranty</li>
<li>Inverter replacement after 10-15 years is main expense</li>
</ul>

<h2>Government Incentives</h2>
<p>Take advantage of available incentives and tax benefits that make solar more affordable than ever. Check with your local authorities for current programs.</p>

<h2>Why 2025 is the Perfect Time</h2>
<ul>
<li>Solar technology is more efficient and affordable</li>
<li>Battery storage options have improved significantly</li>
<li>Rising electricity costs improve ROI</li>
<li>Growing installer network ensures quality service</li>
</ul>

<p>The decision to go solar is no longer a question of "if" but "when." With all these benefits, 2025 might just be your perfect time.</p>',
                'category_id'      => null,
                'author_id'        => $adminUserId,
                'featured_image'   => null,
                'meta_title'       => 'Top 5 Benefits of Going Solar in 2025 | Complete Guide',
                'meta_description' => 'Discover the top 5 benefits of switching to solar power in 2025. Learn about cost savings, property value, and environmental impact.',
                'meta_keywords'    => 'solar benefits, go solar, solar savings, renewable energy, clean energy 2025',
                'views'            => 2156,
                'is_published'     => true,
                'published_at'     => $now->copy()->subDays(20),
                'created_at'       => $now->copy()->subDays(20),
                'updated_at'       => $now->copy()->subDays(20),
            ],
            [
                'title'            => 'Understanding Solar Inverters: Types and Selection Guide',
                'slug'             => 'understanding-solar-inverters-types-selection-guide',
                'excerpt'          => 'Learn about different types of solar inverters and how to choose the right one for your solar power system. A complete technical guide.',
                'content'          => '<p>The inverter is the heart of your solar power system, converting DC power from panels into usable AC power. Understanding your options is crucial.</p>

<h2>Types of Solar Inverters</h2>

<h3>1. String Inverters</h3>
<p>The most common and cost-effective option:</p>
<ul>
<li><strong>Pros:</strong> Lowest cost, proven technology, easy maintenance</li>
<li><strong>Cons:</strong> Performance affected by shading on any panel</li>
<li><strong>Best for:</strong> Unshaded roofs with simple layouts</li>
</ul>

<h3>2. Microinverters</h3>
<p>Individual inverters for each panel:</p>
<ul>
<li><strong>Pros:</strong> Panel-level optimization, better shade performance, modular expansion</li>
<li><strong>Cons:</strong> Higher cost, more components to potentially service</li>
<li><strong>Best for:</strong> Complex roofs with partial shading</li>
</ul>

<h3>3. Hybrid Inverters</h3>
<p>Combine solar and battery storage:</p>
<ul>
<li><strong>Pros:</strong> Battery-ready, backup power capability, future-proof</li>
<li><strong>Cons:</strong> Higher upfront cost</li>
<li><strong>Best for:</strong> Systems planning to add batteries</li>
</ul>

<h2>Key Specifications to Consider</h2>

<h3>Power Rating</h3>
<p>Match inverter size to your panel array. Typical sizing is 1.1-1.3x inverter capacity relative to panel capacity.</p>

<h3>Efficiency</h3>
<p>Look for 96%+ efficiency. Every percentage point matters for long-term production.</p>

<h3>Warranty</h3>
<p>Standard is 5-10 years, but some manufacturers offer up to 25 years. Extended warranties are worth considering.</p>

<h2>Advanced Features</h2>
<ul>
<li><strong>WiFi Monitoring</strong> - Track system performance remotely</li>
<li><strong>MPPT Tracking</strong> - Optimizes power output in varying conditions</li>
<li><strong>Arc Fault Protection</strong> - Enhanced safety features</li>
<li><strong>Grid Support</strong> - Voltage and frequency regulation</li>
</ul>

<h2>Making Your Choice</h2>
<p>Consider your specific needs:</p>
<ul>
<li>Budget constraints</li>
<li>Roof complexity and shading</li>
<li>Future expansion plans</li>
<li>Battery storage intentions</li>
</ul>

<p>Consult with a qualified installer to determine the best inverter type and size for your specific installation.</p>',
                'category_id'      => $invertersCatId,
                'author_id'        => $adminUserId,
                'featured_image'   => null,
                'meta_title'       => 'Solar Inverters Guide 2025 - Types, Selection & Comparison',
                'meta_description' => 'Complete guide to solar inverters. Learn about string inverters, microinverters, and hybrid systems to choose the right one.',
                'meta_keywords'    => 'solar inverter, string inverter, microinverter, hybrid inverter, inverter guide',
                'views'            => 734,
                'is_published'     => true,
                'published_at'     => $now->copy()->subDays(15),
                'created_at'       => $now->copy()->subDays(15),
                'updated_at'       => $now->copy()->subDays(15),
            ],
            [
                'title'            => 'Off-Grid vs Grid-Tied Solar: Which is Right for You?',
                'slug'             => 'off-grid-vs-grid-tied-solar-which-right',
                'excerpt'          => 'Compare off-grid and grid-tied solar systems to determine which solution best fits your energy needs, budget, and lifestyle.',
                'content'          => '<p>One of the first decisions when going solar is choosing between off-grid and grid-tied systems. Each has unique advantages and challenges.</p>

<h2>Grid-Tied Solar Systems</h2>
<p>Connected to the utility grid, these systems feed excess power back to the grid.</p>

<h2>Off-Grid Solar Systems</h2>
<p>Completely independent systems with battery storage for total energy independence.</p>

<p>Your choice depends on location, budget, and energy independence goals. Consult with a solar professional to evaluate your specific situation.</p>',
                'category_id'      => $kitsCatId,
                'author_id'        => $adminUserId,
                'featured_image'   => null,
                'meta_title'       => 'Off-Grid vs Grid-Tied Solar Systems - Complete Comparison 2025',
                'meta_description' => 'Compare off-grid and grid-tied solar systems. Learn costs, benefits, and which option is right for your home.',
                'meta_keywords'    => 'off-grid solar, grid-tied solar, solar systems comparison, hybrid solar',
                'views'            => 1089,
                'is_published'     => true,
                'published_at'     => $now->copy()->subDays(10),
                'created_at'       => $now->copy()->subDays(10),
                'updated_at'       => $now->copy()->subDays(10),
            ],
            [
                'title'            => 'Solar Panel Maintenance: Tips for Optimal Performance',
                'slug'             => 'solar-panel-maintenance-tips-optimal-performance',
                'excerpt'          => 'Keep your solar panels performing at their best with these essential maintenance tips and best practices.',
                'content'          => '<p>Solar panels are remarkably low-maintenance, but proper care ensures optimal performance and longevity.</p>

<h2>Regular Cleaning</h2>
<p>Dust, bird droppings, and debris can reduce efficiency by 5-25%.</p>

<h2>Visual Inspections</h2>
<p>Monthly visual checks can catch issues early.</p>

<p>Remember: A little preventive maintenance goes a long way in ensuring your solar investment continues to provide clean, reliable power for decades.</p>',
                'category_id'      => null,
                'author_id'        => $adminUserId,
                'featured_image'   => null,
                'meta_title'       => 'Solar Panel Maintenance Guide 2025 - Tips & Best Practices',
                'meta_description' => 'Complete solar panel maintenance guide. Learn cleaning tips, inspection schedules, and best practices for optimal performance.',
                'meta_keywords'    => 'solar maintenance, solar panel cleaning, solar care, panel maintenance tips',
                'views'            => 567,
                'is_published'     => true,
                'published_at'     => $now->copy()->subDays(5),
                'created_at'       => $now->copy()->subDays(5),
                'updated_at'       => $now->copy()->subDays(5),
            ],
        ];

        DB::table('blogs')->insert($blogs);

        $this->command->info('Blogs seeded successfully! ' . count($blogs) . ' blogs added.');
    }
}
