<?php
namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Seeds the products table with sample solar products
     *
     * @return void
     */
    public function run(): void
    {
        $now = Carbon::now();

        // Get category IDs
        $solarPanelsCatId       = DB::table('categories')->where('slug', 'solar-panels')->value('id');
        $invertersCatId         = DB::table('categories')->where('slug', 'inverters')->value('id');
        $batteriesCatId         = DB::table('categories')->where('slug', 'batteries')->value('id');
        $chargeControllersCatId = DB::table('categories')->where('slug', 'charge-controllers')->value('id');
        $mountingCatId          = DB::table('categories')->where('slug', 'mounting-systems')->value('id');
        $cablesCatId            = DB::table('categories')->where('slug', 'cables-connectors')->value('id');
        $monitoringCatId        = DB::table('categories')->where('slug', 'monitoring-systems')->value('id');
        $kitsCatId              = DB::table('categories')->where('slug', 'complete-kits')->value('id');

        $products = [
            // Solar Panels
            [
                'name'              => '450W Monocrystalline Solar Panel',
                'slug'              => '450w-monocrystalline-solar-panel',
                'description'       => '<p>High-efficiency monocrystalline solar panel with excellent performance in various weather conditions. Features advanced cell technology for maximum power output and durability.</p><ul><li>Efficiency: 21.5%</li><li>Warranty: 25 years</li><li>Weatherproof design</li><li>Anti-reflective coating</li></ul>',
                'short_description' => 'Premium 450W monocrystalline panel with 21.5% efficiency',
                'sku'               => 'SP-MONO-450W',
                'price'             => 45000,
                'sale_price'        => null,
                'stock_quantity'    => 150,
                'min_stock_level'   => 20,
                'weight'            => 22.5,
                'dimensions'        => json_encode(['length' => 2008, 'width' => 1002, 'height' => 40]),
                'images'            => null,
                'category_id'       => $solarPanelsCatId,
                'agent_id'          => 1,
                'brand'             => 'SunPower Pro',
                'tags'              => json_encode(['monocrystalline', 'high-efficiency', 'residential', 'commercial']),
                'is_featured'       => true,
                'is_active'         => true,
                'meta_title'        => '450W Monocrystalline Solar Panel - High Efficiency',
                'meta_description'  => 'Premium 450W monocrystalline solar panel with 21.5% efficiency and 25-year warranty',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => '350W Polycrystalline Solar Panel',
                'slug'              => '350w-polycrystalline-solar-panel',
                'description'       => '<p>Cost-effective polycrystalline solar panel ideal for residential installations. Reliable performance with excellent value for money.</p><ul><li>Efficiency: 18.2%</li><li>Warranty: 20 years</li><li>Durable frame</li><li>Easy installation</li></ul>',
                'short_description' => 'Affordable 350W polycrystalline panel for residential use',
                'sku'               => 'SP-POLY-350W',
                'price'             => 30000,
                'sale_price'        => 27000,
                'stock_quantity'    => 200,
                'min_stock_level'   => 30,
                'weight'            => 19.8,
                'dimensions'        => json_encode(['length' => 1956, 'width' => 992, 'height' => 40]),
                'images'            => null,
                'category_id'       => $solarPanelsCatId,
                'agent_id'          => 1,
                'brand'             => 'EcoSolar',
                'tags'              => json_encode(['polycrystalline', 'affordable', 'residential']),
                'is_featured'       => true,
                'is_active'         => true,
                'meta_title'        => '350W Polycrystalline Solar Panel - Affordable',
                'meta_description'  => 'Cost-effective 350W polycrystalline solar panel with 20-year warranty',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => '550W Bifacial Solar Panel',
                'slug'              => '550w-bifacial-solar-panel',
                'description'       => '<p>Advanced bifacial solar panel that captures sunlight from both sides for increased energy production. Perfect for commercial installations.</p><ul><li>Efficiency: 22.8%</li><li>Bifacial design</li><li>Warranty: 30 years</li><li>Up to 30% more energy production</li></ul>',
                'short_description' => 'Advanced 550W bifacial panel with dual-side energy capture',
                'sku'               => 'SP-BIFA-550W',
                'price'             => 67500,
                'sale_price'        => null,
                'stock_quantity'    => 85,
                'min_stock_level'   => 15,
                'weight'            => 27.3,
                'dimensions'        => json_encode(['length' => 2278, 'width' => 1134, 'height' => 35]),
                'images'            => null,
                'category_id'       => $solarPanelsCatId,
                'agent_id'          => 1,
                'brand'             => 'PowerMax Elite',
                'tags'              => json_encode(['bifacial', 'high-efficiency', 'commercial', 'premium']),
                'is_featured'       => true,
                'is_active'         => true,
                'meta_title'        => '550W Bifacial Solar Panel - Premium Efficiency',
                'meta_description'  => 'Premium bifacial solar panel with 22.8% efficiency and dual-side energy capture',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // Inverters
            [
                'name'              => '5kW Hybrid Solar Inverter',
                'slug'              => '5kw-hybrid-solar-inverter',
                'description'       => '<p>Intelligent hybrid inverter that manages solar panels, batteries, and grid power seamlessly. Perfect for residential solar systems with battery backup.</p><ul><li>Power: 5000W</li><li>Efficiency: 97.8%</li><li>Built-in MPPT controller</li><li>WiFi monitoring</li><li>Battery compatible</li></ul>',
                'short_description' => 'Smart 5kW hybrid inverter with battery management',
                'sku'               => 'INV-HYB-5KW',
                'price'             => 195000,
                'sale_price'        => null,
                'stock_quantity'    => 45,
                'min_stock_level'   => 10,
                'weight'            => 18.5,
                'dimensions'        => json_encode(['length' => 480, 'width' => 380, 'height' => 165]),
                'images'            => null,
                'category_id'       => $invertersCatId,
                'agent_id'          => 1,
                'brand'             => 'SolarEdge',
                'tags'              => json_encode(['hybrid', 'smart', 'residential', 'battery-compatible']),
                'is_featured'       => true,
                'is_active'         => true,
                'meta_title'        => '5kW Hybrid Solar Inverter - Smart Energy Management',
                'meta_description'  => 'Intelligent 5kW hybrid inverter with battery management and WiFi monitoring',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => '10kW Grid-Tie Solar Inverter',
                'slug'              => '10kw-grid-tie-solar-inverter',
                'description'       => '<p>High-power grid-tie inverter for commercial solar installations. Converts DC power from solar panels to AC power for grid connection.</p><ul><li>Power: 10000W</li><li>Efficiency: 98.5%</li><li>Three-phase output</li><li>Advanced MPPT</li><li>Remote monitoring</li></ul>',
                'short_description' => 'Commercial-grade 10kW grid-tie inverter',
                'sku'               => 'INV-GRID-10KW',
                'price'             => 330000,
                'sale_price'        => 300000,
                'stock_quantity'    => 28,
                'min_stock_level'   => 5,
                'weight'            => 32.4,
                'dimensions'        => json_encode(['length' => 600, 'width' => 450, 'height' => 200]),
                'images'            => null,
                'category_id'       => $invertersCatId,
                'agent_id'          => 1,
                'brand'             => 'Fronius',
                'tags'              => json_encode(['grid-tie', 'commercial', 'three-phase', 'high-power']),
                'is_featured'       => false,
                'is_active'         => true,
                'meta_title'        => '10kW Grid-Tie Solar Inverter - Commercial',
                'meta_description'  => 'High-power 10kW grid-tie inverter for commercial solar installations',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // Batteries
            [
                'name'              => '10kWh Lithium Battery Storage',
                'slug'              => '10kwh-lithium-battery-storage',
                'description'       => '<p>High-capacity lithium iron phosphate battery for residential energy storage. Safe, reliable, and long-lasting.</p><ul><li>Capacity: 10kWh</li><li>Lithium Iron Phosphate</li><li>10-year warranty</li><li>6000+ cycles</li><li>Stackable design</li></ul>',
                'short_description' => 'Premium 10kWh LiFePO4 battery for home energy storage',
                'sku'               => 'BAT-LIPO-10KWH',
                'price'             => 750000,
                'sale_price'        => null,
                'stock_quantity'    => 32,
                'min_stock_level'   => 8,
                'weight'            => 145.0,
                'dimensions'        => json_encode(['length' => 600, 'width' => 400, 'height' => 220]),
                'images'            => null,
                'category_id'       => $batteriesCatId,
                'agent_id'          => 1,
                'brand'             => 'Tesla PowerWall',
                'tags'              => json_encode(['lithium', 'lifepo4', 'residential', 'stackable']),
                'is_featured'       => true,
                'is_active'         => true,
                'meta_title'        => '10kWh Lithium Battery Storage - Home Energy',
                'meta_description'  => 'Premium lithium battery with 10kWh capacity and 10-year warranty',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => '5kWh Battery Module',
                'slug'              => '5kwh-battery-module',
                'description'       => '<p>Compact 5kWh battery module for smaller residential systems. Expandable and efficient.</p><ul><li>Capacity: 5kWh</li><li>Modular design</li><li>5-year warranty</li><li>4000+ cycles</li><li>Easy installation</li></ul>',
                'short_description' => 'Compact 5kWh modular battery system',
                'sku'               => 'BAT-MOD-5KWH',
                'price'             => 420000,
                'sale_price'        => 375000,
                'stock_quantity'    => 55,
                'min_stock_level'   => 12,
                'weight'            => 75.0,
                'dimensions'        => json_encode(['length' => 500, 'width' => 350, 'height' => 180]),
                'images'            => null,
                'category_id'       => $batteriesCatId,
                'agent_id'          => 1,
                'brand'             => 'LG Chem',
                'tags'              => json_encode(['lithium', 'modular', 'compact', 'residential']),
                'is_featured'       => false,
                'is_active'         => true,
                'meta_title'        => '5kWh Battery Module - Compact Storage',
                'meta_description'  => 'Compact and modular 5kWh battery for residential solar systems',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // Charge Controllers
            [
                'name'              => '60A MPPT Charge Controller',
                'slug'              => '60a-mppt-charge-controller',
                'description'       => '<p>Advanced MPPT charge controller for optimal battery charging efficiency. Features LCD display and multiple protection systems.</p><ul><li>Current: 60A</li><li>MPPT technology</li><li>LCD display</li><li>Multiple protection</li><li>12V/24V/48V compatible</li></ul>',
                'short_description' => 'Professional 60A MPPT controller with LCD display',
                'sku'               => 'CC-MPPT-60A',
                'price'             => 58500,
                'sale_price'        => null,
                'stock_quantity'    => 75,
                'min_stock_level'   => 15,
                'weight'            => 3.2,
                'dimensions'        => json_encode(['length' => 280, 'width' => 180, 'height' => 95]),
                'images'            => null,
                'category_id'       => $chargeControllersCatId,
                'agent_id'          => 1,
                'brand'             => 'Victron Energy',
                'tags'              => json_encode(['mppt', 'charge-controller', 'lcd', 'professional']),
                'is_featured'       => true,
                'is_active'         => true,
                'meta_title'        => '60A MPPT Charge Controller - Professional Grade',
                'meta_description'  => 'Advanced 60A MPPT charge controller with LCD display and multiple protections',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // Mounting Systems
            [
                'name'              => 'Roof Mount Kit for 10 Panels',
                'slug'              => 'roof-mount-kit-10-panels',
                'description'       => '<p>Complete aluminum mounting kit for installing 10 solar panels on pitched roofs. Includes all necessary hardware and rails.</p><ul><li>Capacity: 10 panels</li><li>Aluminum construction</li><li>Adjustable angle</li><li>Complete hardware kit</li><li>25-year warranty</li></ul>',
                'short_description' => 'Complete aluminum roof mounting kit for 10 panels',
                'sku'               => 'MNT-ROOF-10P',
                'price'             => 90000,
                'sale_price'        => 82500,
                'stock_quantity'    => 42,
                'min_stock_level'   => 10,
                'weight'            => 48.5,
                'dimensions'        => json_encode(['length' => 1200, 'width' => 800, 'height' => 150]),
                'images'            => null,
                'category_id'       => $mountingCatId,
                'agent_id'          => 1,
                'brand'             => 'IronRidge',
                'tags'              => json_encode(['mounting', 'roof', 'aluminum', 'kit']),
                'is_featured'       => false,
                'is_active'         => true,
                'meta_title'        => 'Roof Mount Kit for 10 Solar Panels',
                'meta_description'  => 'Complete aluminum mounting system for 10 solar panels with 25-year warranty',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // Cables & Connectors
            [
                'name'              => '50m Solar Cable 6mm² Red/Black',
                'slug'              => '50m-solar-cable-6mm-red-black',
                'description'       => '<p>UV-resistant solar cable for outdoor installations. Includes both red and black cables (25m each).</p><ul><li>Length: 50m (25m red + 25m black)</li><li>Cross-section: 6mm²</li><li>UV resistant</li><li>Temperature range: -40°C to +90°C</li><li>Weatherproof</li></ul>',
                'short_description' => '50m professional solar cable set (6mm²)',
                'sku'               => 'CBL-SOL-6MM-50M',
                'price'             => 13500,
                'sale_price'        => null,
                'stock_quantity'    => 125,
                'min_stock_level'   => 25,
                'weight'            => 8.5,
                'dimensions'        => json_encode(['length' => 300, 'width' => 300, 'height' => 200]),
                'images'            => null,
                'category_id'       => $cablesCatId,
                'agent_id'          => 1,
                'brand'             => 'Helukabel',
                'tags'              => json_encode(['cable', 'wire', 'uv-resistant', 'outdoor']),
                'is_featured'       => false,
                'is_active'         => true,
                'meta_title'        => '50m Solar Cable 6mm² - UV Resistant',
                'meta_description'  => 'Professional UV-resistant solar cable for outdoor installations',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // Monitoring Systems
            [
                'name'              => 'WiFi Solar Monitoring System',
                'slug'              => 'wifi-solar-monitoring-system',
                'description'       => '<p>Smart monitoring system for real-time tracking of your solar system performance. Mobile app included.</p><ul><li>Real-time monitoring</li><li>WiFi connectivity</li><li>Mobile app (iOS/Android)</li><li>Email alerts</li><li>Historical data analysis</li></ul>',
                'short_description' => 'Smart WiFi monitoring with mobile app',
                'sku'               => 'MON-WIFI-01',
                'price'             => 37500,
                'sale_price'        => 30000,
                'stock_quantity'    => 68,
                'min_stock_level'   => 15,
                'weight'            => 0.5,
                'dimensions'        => json_encode(['length' => 120, 'width' => 80, 'height' => 35]),
                'images'            => null,
                'category_id'       => $monitoringCatId,
                'agent_id'          => 1,
                'brand'             => 'Solar-Log',
                'tags'              => json_encode(['monitoring', 'wifi', 'smart', 'app']),
                'is_featured'       => false,
                'is_active'         => true,
                'meta_title'        => 'WiFi Solar Monitoring System - Real-time Tracking',
                'meta_description'  => 'Smart monitoring system with WiFi and mobile app for solar systems',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // Complete Kits
            [
                'name'              => '3kW Complete Solar Power Kit',
                'slug'              => '3kw-complete-solar-power-kit',
                'description'       => '<p>All-in-one solar power kit perfect for small residential installations. Includes panels, inverter, mounting, cables, and all necessary components.</p><ul><li>System size: 3kW</li><li>8x 375W panels</li><li>3kW hybrid inverter</li><li>Mounting hardware</li><li>All cables and connectors</li><li>Installation guide</li></ul>',
                'short_description' => 'Complete 3kW solar system - ready to install',
                'sku'               => 'KIT-3KW-COMP',
                'price'             => 675000,
                'sale_price'        => 600000,
                'stock_quantity'    => 18,
                'min_stock_level'   => 5,
                'weight'            => 250.0,
                'dimensions'        => json_encode(['length' => 2100, 'width' => 1100, 'height' => 300]),
                'images'            => null,
                'category_id'       => $kitsCatId,
                'agent_id'          => 1,
                'brand'             => 'EcoPower Complete',
                'tags'              => json_encode(['complete-kit', 'residential', '3kw', 'all-in-one']),
                'is_featured'       => true,
                'is_active'         => true,
                'meta_title'        => '3kW Complete Solar Power Kit - All-in-One',
                'meta_description'  => 'Complete 3kW solar system with panels, inverter, mounting, and all components',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'name'              => '5kW Off-Grid Solar Kit',
                'slug'              => '5kw-off-grid-solar-kit',
                'description'       => '<p>Comprehensive off-grid solar kit for remote locations or complete energy independence. Includes batteries and charge controller.</p><ul><li>System size: 5kW</li><li>12x 420W panels</li><li>5kW inverter</li><li>10kWh battery</li><li>MPPT charge controller</li><li>Complete mounting system</li></ul>',
                'short_description' => 'Complete 5kW off-grid system with batteries',
                'sku'               => 'KIT-5KW-OFFGRID',
                'price'             => 1950000,
                'sale_price'        => null,
                'stock_quantity'    => 8,
                'min_stock_level'   => 3,
                'weight'            => 520.0,
                'dimensions'        => json_encode(['length' => 2200, 'width' => 1200, 'height' => 400]),
                'images'            => null,
                'category_id'       => $kitsCatId,
                'agent_id'          => 1,
                'brand'             => 'OffGrid Solutions',
                'tags'              => json_encode(['complete-kit', 'off-grid', '5kw', 'battery-included']),
                'is_featured'       => true,
                'is_active'         => true,
                'meta_title'        => '5kW Off-Grid Solar Kit - Complete Independence',
                'meta_description'  => 'Complete 5kW off-grid solar system with batteries for energy independence',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
        ];

        DB::table('products')->insert($products);

        $this->command->info('Products seeded successfully! ' . count($products) . ' products added.');
    }
}
